const FOOD_JSON = [
  {"name": "가지", "type": "채소", "img": "assets/imgs/food/vegetable/gaji.png"},
  {"name": "감자", "type": "채소", "img": "assets/imgs/food/vegetable/gamja.png"},
  {"name": "버섯", "type": "채소", "img": "assets/imgs/food/vegetable/busut.png"},
  {"name": "고구마", "type": "채소", "img": "assets/imgs/food/vegetable/goguma.png"},
  {"name": "고추", "type": "채소", "img": "assets/imgs/food/vegetable/gochu.png"},
  {"name": "깻잎", "type": "채소", "img": "assets/imgs/food/vegetable/ggatip.png"},
  {"name": "상추", "type": "채소", "img": "assets/imgs/food/vegetable/sangchu.png"},
  {"name": "나물", "type": "채소", "img": "assets/imgs/food/vegetable/namul.png"},
  {"name": "고사리", "type": "채소", "img": "assets/imgs/food/vegetable/gosari.png"},
  {"name": "미나리", "type": "채소", "img": "assets/imgs/food/vegetable/minari.png"},
  {"name": "도라지", "type": "채소", "img": "assets/imgs/food/vegetable/doraji.png"},
  {"name": "마늘", "type": "채소", "img": "assets/imgs/food/vegetable/meneul.png"},
  {"name": "생강", "type": "채소", "img": "assets/imgs/food/vegetable/sanggang.png"},
  {"name": "단호박", "type": "채소", "img": "assets/imgs/food/vegetable/danhobak.png"},
  {"name": "호박", "type": "채소", "img": "assets/imgs/food/vegetable/hobak.png"},
  {"name": "애호박", "type": "채소", "img": "assets/imgs/food/vegetable/ahhobak.png"},
  {"name": "당근", "type": "채소", "img": "assets/imgs/food/vegetable/danggeun.png"},
  {"name": "무", "type": "채소", "img": "assets/imgs/food/vegetable/mu.png"},
  {"name": "배추", "type": "채소", "img": "assets/imgs/food/vegetable/baechu.png"},
  {"name": "브로콜리", "type": "채소", "img": "assets/imgs/food/vegetable/brocorly.png"},
  {"name": "시금치", "type": "채소", "img": "assets/imgs/food/vegetable/sigeumchi.png"},
  {"name": "청경채", "type": "채소", "img": "assets/imgs/food/vegetable/chyunggyungchae.png"},
  {"name": "새싹채소", "type": "채소", "img": "assets/imgs/food/vegetable/sasak.png"},
  {"name": "아스파라거스", "type": "채소", "img": "assets/imgs/food/vegetable/ahseparagus.png"},
  {"name": "양배추", "type": "채소", "img": "assets/imgs/food/vegetable/yangbaechu.png"},
  {"name": "양상추", "type": "채소", "img": "assets/imgs/food/vegetable/yangsangchu.png"},
  {"name": "양파", "type": "채소", "img": "assets/imgs/food/vegetable/yangfa.png"},
  {"name": "연근", "type": "채소", "img": "assets/imgs/food/vegetable/yeongeon.png"},
  {"name": "우엉", "type": "채소", "img": "assets/imgs/food/vegetable/woung.png"},
  {"name": "옥수수", "type": "채소", "img": "assets/imgs/food/vegetable/oksusu.png"},
  {"name": "콩나물", "type": "채소", "img": "assets/imgs/food/vegetable/kongnamul.png"},
  {"name": "파", "type": "채소", "img": "assets/imgs/food/vegetable/pa.png"},
  {"name": "부추", "type": "채소", "img": "assets/imgs/food/vegetable/buchu.png"},
  {"name": "파프리카", "type": "채소", "img": "assets/imgs/food/vegetable/pafrica.png"},
  {"name": "피망", "type": "채소", "img": "assets/imgs/food/vegetable/fimang.png"},
  {"name": "오이", "type": "채소", "img": "assets/imgs/food/vegetable/oi.png"},
  {"name": "귤", "type": "과일", "img": "assets/imgs/food/fruit/gyul.png"},
  {"name": "딸기", "type": "과일", "img": "assets/imgs/food/fruit/ddalgi.png"},
  {"name": "레몬", "type": "과일", "img": "assets/imgs/food/fruit/lemon.png"},
  {"name": "바나나", "type": "과일", "img": "assets/imgs/food/fruit/banana.png"},
  {"name": "방울토마토", "type": "과일", "img": "assets/imgs/food/fruit/bangultomato.png"},
  {"name": "배", "type": "과일", "img": "assets/imgs/food/fruit/bae.png"},
  {"name": "사과", "type": "과일", "img": "assets/imgs/food/fruit/apple.png"},
  {"name": "오렌지", "type": "과일", "img": "assets/imgs/food/fruit/orange.png"},
  {"name": "토마토", "type": "과일", "img": "assets/imgs/food/fruit/tomato.png"},
  {"name": "파인애플", "type": "과일", "img": "assets/imgs/food/fruit/pineapple.png"},
  {"name": "포도", "type": "과일", "img": "assets/imgs/food/fruit/podo.png"},
  {"name": "아보카도", "type": "과일", "img": "assets/imgs/food/fruit/abocardo.png"},
  {
    "name": "계란",
    "type": "육류",
    "img": "assets/imgs/food/meat/egg.png",
    "similarNames": ["달걀"]
  },
  {"name": "닭고기", "type": "육류", "img": "assets/imgs/food/meat/dakgogi.png"},
  {"name": "닭가슴살", "type": "육류", "order": 1, "img": "assets/imgs/food/meat/dakgaseumsal.png"},
  {"name": "돼지고기", "type": "육류", "img": "assets/imgs/food/meat/pig.png"},
  {
    "name": "삼겹살",
    "type": "육류",
    "order": 1,
    "img": "assets/imgs/food/meat/samgyupsal.png",
    "similarNames": ["삼겹"]
  },
  {
    "name": "목살",
    "type": "육류",
    "order": 1,
    "img": "assets/imgs/food/meat/moksal.png",
    "similarNames": ["목심"]
  },
  {"name": "앞다리", "type": "육류", "order": 1, "img": "assets/imgs/food/meat/apdarisal.png"},
  {"name": "뒷다리", "type": "육류", "order": 1, "img": "assets/imgs/food/meat/dytdarisal.png"},
  {"name": "소고기", "type": "육류", "img": "assets/imgs/food/meat/sogogi.png"},
  {"name": "등심", "type": "육류", "order": 1, "img": "assets/imgs/food/meat/dengsim.png"},
  {"name": "안심", "type": "육류", "order": 1, "img": "assets/imgs/food/meat/ansim.png"},
  {"name": "채끝", "type": "육류", "order": 1, "img": "assets/imgs/food/meat/chaegget.png"},
  {"name": "국거리", "type": "육류", "order": 2, "img": "assets/imgs/food/meat/gukguri.png"},
  {"name": "양고기", "type": "육류", "img": "assets/imgs/food/meat/yanggogi.png"},
  {"name": "오리고기", "type": "육류", "img": "assets/imgs/food/meat/ohrigogi.png"},
  {"name": "게", "type": "수산물", "img": "assets/imgs/food/seafood/gae.png"},
  {"name": "미역", "type": "수산물", "img": "assets/imgs/food/seafood/miyuk.png"},
  {"name": "새우", "type": "수산물", "img": "assets/imgs/food/seafood/saewoo.png"},
  {"name": "고등어", "type": "수산물", "img": "assets/imgs/food/seafood/godenguh.png"},
  {"name": "갈치", "type": "수산물", "img": "assets/imgs/food/seafood/galchi.png"},
  {"name": "꽁치", "type": "수산물", "img": "assets/imgs/food/seafood/ggongchi.png"},
  {"name": "멸치", "type": "수산물", "img": "assets/imgs/food/seafood/myulchi.png"},
  {"name": "오징어", "type": "수산물", "img": "assets/imgs/food/seafood/ohjinguh.png"},
  {"name": "문어", "type": "수산물", "img": "assets/imgs/food/seafood/moonuh.png"},
  {"name": "조개", "type": "수산물", "img": "assets/imgs/food/seafood/jogae.png"},
  {"name": "대구", "type": "수산물", "img": "assets/imgs/food/seafood/daegu.png"},
  {"name": "연어", "type": "수산물", "img": "assets/imgs/food/seafood/yeonuh.png"},
  {"name": "전복", "type": "수산물", "img": "assets/imgs/food/seafood/junbok.png"},
  {"name": "장어", "type": "수산물", "img": "assets/imgs/food/seafood/janguh.png"},
  {"name": "황태", "type": "수산물", "img": "assets/imgs/food/seafood/hwangtae.png"},
  {"name": "홍합", "type": "수산물", "img": "assets/imgs/food/seafood/honghap.png"},
  {"name": "골뱅이", "type": "수산물", "img": "assets/imgs/food/seafood/golbangyi.png"},
  {"name": "바지락", "type": "수산물", "img": "assets/imgs/food/seafood/bajirock.png"},
  {"name": "낙지", "type": "수산물", "img": "assets/imgs/food/seafood/nakji.png"},
  {"name": "쭈꾸미", "type": "수산물", "img": "assets/imgs/food/seafood/jjukumi.png"},
  {"name": "깨", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/sesame.png"},
  {"name": "고춧가루", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/red_pepper_powder.png"},
  {"name": "버터", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/butter.png"},
  {"name": "머스타드", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/mustard.png"},
  {"name": "마요네즈", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/mayonnaise.png"},
  {"name": "케찹", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/Ketchup.png"},
  {"name": "설탕", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/sugar.png"},
  {"name": "후추", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/pepper.png"},
  {"name": "소금", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/salt.png"},
  {"name": "쌈장", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/Ssamjang.png"},
  {"name": "청국장", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/soybean_paste.png"},
  {"name": "된장", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/soybean_paste.png"},
  {"name": "식초", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/vinegar.png"},
  {"name": "식용유", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/cooking_oil.png"},
  {"name": "참기름", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/sesame_oil.png"},
  {"name": "올리브유", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/olive_oil.png"},
  {"name": "물엿", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/starch_syrup.png"},
  {"name": "꿀", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/honey.png"},
  {"name": "굴소스", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/Oyster_sauce.png"},
  {"name": "초고추장", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/srpepperpaste.png"},
  {"name": "고추장", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/gochujang.png"},
  {"name": "간장", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/ganjang.png"},
  {"name": "액젓", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/akjut.png"},
  {"name": "새우젓", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/saewoojut.png"},
  {"name": "간마늘", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/groundgarlic.png"},
  {"name": "쯔유", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/jjeuyu.png"},
  {"name": "겨자", "type": "조미료/향신료", "img": "assets/imgs/food/seasoning/gyeoja.png"},
  {"name": "두부", "type": "가공/유제품", "img": "assets/imgs/food/pnd/dobu.png"},
  {"name": "라면", "type": "가공/유제품", "img": "assets/imgs/food/pnd/ramen.png"},
  {"name": "떡", "type": "가공/유제품", "img": "assets/imgs/food/pnd/dduk.png"},
  {"name": "베이컨", "type": "가공/유제품", "img": "assets/imgs/food/pnd/bacon.png"},
  {"name": "햄", "type": "가공/유제품", "img": "assets/imgs/food/pnd/ham.png"},
  {"name": "치즈", "type": "가공/유제품", "img": "assets/imgs/food/pnd/cheeze.png"},
  {"name": "참치", "type": "가공/유제품", "img": "assets/imgs/food/pnd/chamchi.png"},
  {"name": "밀가루", "type": "가공/유제품", "img": "assets/imgs/food/pnd/mealgaru.png"},
  {"name": "부침가루", "type": "가공/유제품", "img": "assets/imgs/food/pnd/buchimgaru.png"},
  {"name": "튀김가루", "type": "가공/유제품", "img": "assets/imgs/food/pnd/tuigimgaru.png"},
  {"name": "우유", "type": "가공/유제품", "img": "assets/imgs/food/pnd/milk.png"},
  {"name": "어묵", "type": "가공/유제품", "img": "assets/imgs/food/pnd/uhmook.png"},
  {"name": "파스타", "type": "가공/유제품", "img": "assets/imgs/food/pnd/pasta.png"},
  {"name": "김치", "type": "가공/유제품", "img": "assets/imgs/food/pnd/gimchi.png"},
  {"name": "국수", "type": "가공/유제품", "img": "assets/imgs/food/pnd/guksoo.png"},
  {"name": "김", "type": "가공/유제품", "img": "assets/imgs/food/pnd/gim.png"}
];
