// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWVewuc577PIN2oO40a9K4i9bzdixoHZk',
    appId: '1:992466273542:web:fd4354bfe7fa50ec434a87',
    messagingSenderId: '992466273542',
    projectId: 'recipe-inventory',
    authDomain: 'recipe-inventory.firebaseapp.com',
    storageBucket: 'recipe-inventory.firebasestorage.app',
    measurementId: 'G-WG0BZ3MFYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq9v_jowp1ma_bafqYEtjrU7gbSs1tHmE',
    appId: '1:992466273542:android:7aae1163a2e7aded434a87',
    messagingSenderId: '992466273542',
    projectId: 'recipe-inventory',
    storageBucket: 'recipe-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKJOEDSPSo4fIYkvNuF-98nRalu-u7d0',
    appId: '1:992466273542:ios:3139744393d3f711434a87',
    messagingSenderId: '992466273542',
    projectId: 'recipe-inventory',
    storageBucket: 'recipe-inventory.firebasestorage.app',
    iosClientId: '992466273542-p8d26jagl9n5hppcjdro1q4bfa95oh1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIKJOEDSPSo4fIYkvNuF-98nRalu-u7d0',
    appId: '1:992466273542:ios:3139744393d3f711434a87',
    messagingSenderId: '992466273542',
    projectId: 'recipe-inventory',
    storageBucket: 'recipe-inventory.firebasestorage.app',
    iosClientId: '992466273542-p8d26jagl9n5hppcjdro1q4bfa95oh1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWVewuc577PIN2oO40a9K4i9bzdixoHZk',
    appId: '1:992466273542:web:db1f8424e81fd3fd434a87',
    messagingSenderId: '992466273542',
    projectId: 'recipe-inventory',
    authDomain: 'recipe-inventory.firebaseapp.com',
    storageBucket: 'recipe-inventory.firebasestorage.app',
    measurementId: 'G-E3SD7BXQ2M',
  );

}